// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdkmcyjayefpltoekzyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNka21jeWpheWVmcGx0b2VrenlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NTc3MDUsImV4cCI6MjA2ODEzMzcwNX0.Xnp0wWfyvywJZy4p6ABZY8SwfisdDEDEdRMkpMEIVtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});